name = "storefront"
compatibility_date = "2023-10-12"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "./.vercel/output/static"

[vars]
NEXT_PUBLIC_SALEOR_API_URL = "https://api.skozix.com/graphql/"
NEXT_PUBLIC_STOREFRONT_URL = "https://store.skozix.com"
NODE_ENV = "development"
